version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/db_win
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres_win
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: db_win
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_win:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    
  redis:
    image: redis:latest
    container_name: my-redis-instance
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass my_redis_password
    environment:
      - REDIS_PASSWORD=my_redis_password
      - REDIS_NAME=my-redis-instance
      - REDIS_PORT=6379
      - REDIS_HOST=localhost
      - REDIS_DATABASE=0
  mongo:
    image: mongo:latest 
    container_name: mongodb_container 
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_win:
  redis_data:
  mongo_data: